AWSTemplateFormatVersion: 2010-09-09
Description: Create an S3 bucket with a parameterized name and return the bucket ARN.

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to create
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "^[a-z0-9.-]+$"
    ConstraintDescription: "Bucket name must be lowercase, alphanumeric, dots or hyphens."

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"
